#!/usr/bin/env bash

function gerrit_help {
    echo "Usage: git gerrit [ draft | publish | rebase | help ]"
    exit 1
}

function gerrit_draft {
    git push origin HEAD:refs/drafts/master
}

function gerrit_publish {
    git push origin HEAD:refs/for/master
}

function gerrit_rebase {
    git fetch
    git rebase origin/master
}

[[ $# -ne 1  ]] && gerrit_help

command=$1

[[ "x$command" == "xdraft" ]] && gerrit_draft
[[ "x$command" == "xpublish" ]] && gerrit_publish
[[ "x$command" == "xpush" ]] && gerrit_push
[[ "x$command" == "xrebase" ]] && gerrit_rebase
[[ "x$command" == "xhelp" ]] && gerrit_help

