#!/usr/bin/env bash

workspace=$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)
project=$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)

[ -d "$workspace" ] && open $workspace || echo "No Xcode workspace found. Trying project..."
[ -d "$project" ] && open $project || echo "No Xcode project found. Sorry."

