#!/usr/bin/env bash

workspace=$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)
project=$(find . -maxdepth 1 -name '*.xcodeproj' -print -quit)

if [ -d "$workspace" ]; then
    open $workspace
elif [ -d "$project" ]; then
    open $project
else
    echo "Sorry. Nothing to open on Xcode here..."
fi
